HOST = "127.0.0.1"
PORT = 12345
SAMPLING_RATE = 130  # HZ
VALUES_IN_PACKET_COUNT = int(SAMPLING_RATE / 2)  # send packet twice a second
VALUE_SIZE = 4
TIMESTAMP_SIZE = 8
SINGLE_ENTRY_SIZE = VALUE_SIZE + TIMESTAMP_SIZE
CSV_PATH = "data/arkusz_rsa7.csv"

PRINT_ECG_DATA = True

NEGATE_INCOMING_DATA = False

### TEST DATA SETTINGS
RUN_TEST_DATA = True
NORMALIZED_TEST_DATA_TIME = True

###

### PLOT SETTINGS


###
