HOST = "127.0.0.1"
PORT = 12345
SAMPLING_RATE = 130  # HZ
VALUES_IN_PACKET_COUNT = int(SAMPLING_RATE / 2) #send packet twice a second
CSV_PATH = "data/ecg_data1.csv"

PRINT_ECG_DATA = True

### TEST DATA SETTINGS
RUN_TEST_DATA = True
NORMALIZED_TEST_DATA_TIME = True

###

### PLOT SETTINGS


###